/*
  Definitions for the A-Traps in the ROM.
  Creaated 2018, Eric Knudstrup.
*/
#ifndef TOOLBOX_TRAPS_H
#define TOOLBOX_TRAPS_H

#define ATRAP_TETextBox	0xA9CE
#define ATRAP_TextBox	0xA9CE
#define ATRAP_TESetText	0xA9CF
#define ATRAP_TECalText	0xA9D0
#define ATRAP_TESetSelect	0xA9D1
#define ATRAP_TENew	0xA9D2
#define ATRAP_TEUpdate	0xA9D3
#define ATRAP_TEClick	0xA9D4
#define ATRAP_TECopy	0xA9D5
#define ATRAP_TECut	0xA9D6
#define ATRAP_TEDelete	0xA9D7
#define ATRAP_TEActivate	0xA9D8
#define ATRAP_TEDeactivate	0xA9D9
#define ATRAP_TEIdle	0xA9DA
#define ATRAP_TEPaste	0xA9DB
#define ATRAP_TEKey	0xA9DC
#define ATRAP_TEScroll	0xA9DD
#define ATRAP_TEInsert	0xA9DE
#define ATRAP_TESetAlignment	0xA9DF
#define ATRAP_TESetJust	0xA9DF
#define ATRAP_Munger	0xA9E0
#define ATRAP_HandToHand	0xA9E1
#define ATRAP_PtrToXHand	0xA9E2
#define ATRAP_PtrToHand	0xA9E3
#define ATRAP_HandAndHand	0xA9E4
#define ATRAP_InitPack	0xA9E5
#define ATRAP_InitAllPacks	0xA9E6
#define ATRAP_Pack0	0xA9E7
#define ATRAP_Pack1	0xA9E8
#define ATRAP_Pack2	0xA9E9
#define ATRAP_Pack3	0xA9EA
#define ATRAP_FP68K	0xA9EB
#define ATRAP_Pack4	0xA9EB
#define ATRAP_Elems68K	0xA9EC
#define ATRAP_Pack5	0xA9EC
#define ATRAP_Pack6	0xA9ED
#define ATRAP_DECSTR68K	0xA9EE
#define ATRAP_Pack7	0xA9EE
#define ATRAP_PtrAndHand	0xA9EF
#define ATRAP_LoadSeg	0xA9F0
#define ATRAP_UnLoadSeg	0xA9F1
#define ATRAP_Launch	0xA9F2
#define ATRAP_Chain	0xA9F3
#define ATRAP_ExitToShell	0xA9F4
#define ATRAP_GetAppParms	0xA9F5
#define ATRAP_GetResFileAttrs	0xA9F6
#define ATRAP_SetResFileAttrs	0xA9F7
#define ATRAP_MethodDispatch	0xA9F8
#define ATRAP_InfoScrap	0xA9F9
#define ATRAP_UnloadScrap	0xA9FA
#define ATRAP_UnlodeScrap	0xA9FA
#define ATRAP_LoadScrap	0xA9FB
#define ATRAP_LodeScrap	0xA9FB
#define ATRAP_ZeroScrap	0xA9FC
#define ATRAP_GetScrap	0xA9FD
#define ATRAP_PutScrap	0xA9FE
#define ATRAP_Debugger	0xA9FF
#define ATRAP_OpenCPort	0xAA00
#define ATRAP_InitCPort	0xAA01
#define ATRAP_NewPixMap	0xAA03
#define ATRAP_DisposPixMap	0xAA04
#define ATRAP_DisposePixMap	0xAA04
#define ATRAP_CopyPixMap	0xAA05
#define ATRAP_SetPortPix	0xAA06
#define ATRAP_NewPixPat	0xAA07
#define ATRAP_DisposPixPat	0xAA08
#define ATRAP_DisposePixPat	0xAA08
#define ATRAP_CopyPixPat	0xAA09
#define ATRAP_PenPixPat	0xAA0A
#define ATRAP_BackPixPat	0xAA0B
#define ATRAP_GetPixPat	0xAA0C
#define ATRAP_MakeRGBPat	0xAA0D
#define ATRAP_FillCRect	0xAA0E
#define ATRAP_FillCOval	0xAA0F
#define ATRAP_FillCRoundRect	0xAA10
#define ATRAP_FillCArc	0xAA11
#define ATRAP_FillCRgn	0xAA12
#define ATRAP_FillCPoly	0xAA13
#define ATRAP_RGBForeColor	0xAA14
#define ATRAP_RGBBackColor	0xAA15
#define ATRAP_SetCPixel	0xAA16
#define ATRAP_GetCPixel	0xAA17
#define ATRAP_GetCTable	0xAA18
#define ATRAP_GetForeColor	0xAA19
#define ATRAP_GetBackColor	0xAA1A
#define ATRAP_GetCCursor	0xAA1B
#define ATRAP_SetCCursor	0xAA1C
#define ATRAP_AllocCursor	0xAA1D
#define ATRAP_GetCIcon	0xAA1E
#define ATRAP_PlotCIcon	0xAA1F
#define ATRAP_OpenCPicture	0xAA20
#define ATRAP_OpColor	0xAA21
#define ATRAP_HiliteColor	0xAA22
#define ATRAP_CharExtra	0xAA23
#define ATRAP_DisposCTable	0xAA24
#define ATRAP_DisposeCTable	0xAA24
#define ATRAP_DisposCIcon	0xAA25
#define ATRAP_DisposeCIcon	0xAA25
#define ATRAP_DisposCCursor	0xAA26
#define ATRAP_DisposeCCursor	0xAA26
#define ATRAP_GetMaxDevice	0xAA27
#define ATRAP_GetCTSeed	0xAA28
#define ATRAP_GetDeviceList	0xAA29
#define ATRAP_GetMainDevice	0xAA2A
#define ATRAP_GetNextDevice	0xAA2B
#define ATRAP_TestDeviceAttribute	0xAA2C
#define ATRAP_SetDeviceAttribute	0xAA2D
#define ATRAP_InitGDevice	0xAA2E
#define ATRAP_NewGDevice	0xAA2F
#define ATRAP_DisposGDevice	0xAA30
#define ATRAP_DisposeGDevice	0xAA30
#define ATRAP_SetGDevice	0xAA31
#define ATRAP_GetGDevice	0xAA32
#define ATRAP_Color2Index	0xAA33
#define ATRAP_Index2Color	0xAA34
#define ATRAP_InvertColor	0xAA35
#define ATRAP_RealColor	0xAA36
#define ATRAP_GetSubTable	0xAA37
#define ATRAP_UpdatePixMap	0xAA38
#define ATRAP_MakeITable	0xAA39
#define ATRAP_AddSearch	0xAA3A
#define ATRAP_AddComp	0xAA3B
#define ATRAP_SetClientID	0xAA3C
#define ATRAP_ProtectEntry	0xAA3D
#define ATRAP_ReserveEntry	0xAA3E
#define ATRAP_SetEntries	0xAA3F
#define ATRAP_QDError	0xAA40
#define ATRAP_SetWinColor	0xAA41
#define ATRAP_GetAuxWin	0xAA42
#define ATRAP_SetControlColor	0xAA43
#define ATRAP_SetCtlColor	0xAA43
#define ATRAP_GetAuxCtl	0xAA44
#define ATRAP_GetAuxiliaryControlRecord	0xAA44
#define ATRAP_NewCWindow	0xAA45
#define ATRAP_GetNewCWindow	0xAA46
#define ATRAP_SetDeskCPat	0xAA47
#define ATRAP_GetCWMgrPort	0xAA48
#define ATRAP_SaveEntries	0xAA49
#define ATRAP_RestoreEntries	0xAA4A
#define ATRAP_NewCDialog	0xAA4B
#define ATRAP_NewColorDialog	0xAA4B
#define ATRAP_DelSearch	0xAA4C
#define ATRAP_DelComp	0xAA4D
#define ATRAP_SetStdCProcs	0xAA4E
#define ATRAP_CalcCMask	0xAA4F
#define ATRAP_SeedCFill	0xAA50
#define ATRAP_CopyDeepMask	0xAA51
#define ATRAP_HFSPinaforeDispatch	0xAA52
#define ATRAP_HighLevelFSDispatch	0xAA52
#define ATRAP_DictionaryDispatch	0xAA53
#define ATRAP_TextServicesDispatch	0xAA54
#define ATRAP_DockingDispatch	0xAA57
#define ATRAP_MixedModeDispatch	0xAA59
#define ATRAP_CodeFragmentDispatch	0xAA5A
#define ATRAP_DelMCEntries	0xAA60
#define ATRAP_DeleteMCEntries	0xAA60
#define ATRAP_GetMCInfo	0xAA61
#define ATRAP_SetMCInfo	0xAA62
#define ATRAP_DispMCInfo	0xAA63
#define ATRAP_DisposeMCInfo	0xAA63
#define ATRAP_GetMCEntry	0xAA64
#define ATRAP_SetMCEntries	0xAA65
#define ATRAP_MenuChoice	0xAA66
#define ATRAP_DialogDispatch	0xAA68
#define ATRAP_InitPalettes	0xAA90
#define ATRAP_NewPalette	0xAA91
#define ATRAP_GetNewPalette	0xAA92
#define ATRAP_DisposePalette	0xAA93
#define ATRAP_ActivatePalette	0xAA94
#define ATRAP_NSetPalette	0xAA95
#define ATRAP_SetPalette	0xAA95
#define ATRAP_GetPalette	0xAA96
#define ATRAP_PmForeColor	0xAA97
#define ATRAP_PmBackColor	0xAA98
#define ATRAP_AnimateEntry	0xAA99
#define ATRAP_AnimatePalette	0xAA9A
#define ATRAP_GetEntryColor	0xAA9B
#define ATRAP_SetEntryColor	0xAA9C
#define ATRAP_GetEntryUsage	0xAA9D
#define ATRAP_SetEntryUsage	0xAA9E
#define ATRAP_CTab2Palette	0xAA9F
#define ATRAP_Palette2CTab	0xAAA0
#define ATRAP_CopyPalette	0xAAA1
#define ATRAP_PaletteDispatch	0xAAA2
#define ATRAP_CursorDeviceDispatch	0xAADB
#define ATRAP_QDExtensions	0xAB1D
#define ATRAP_NQDMisc	0xABC3
#define ATRAP_IconDispatch	0xABC9
#define ATRAP_DeviceLoop	0xABCA
#define ATRAP_DisplayDispatch	0xABEB
#define ATRAP_ThreadDispatch	0xABF2
#define ATRAP_StdOpcodeProc	0xABF8
#define ATRAP_TranslationDispatch	0xABFC
#define ATRAP_DebugStr	0xABFF

#endif
